export type ResearchTopic = {
  topic_id: string;
  title: string;
  category: string;
  scene: string;
  target_user: string;
  level: string;
  prep_seconds: number;
  answer_seconds: number;
  core_skill: string;
  background: string;
  prompt: string;
  followups: string;
  support_direction: string;
  challenge_direction: string;
  conditional_view: string;
  personal_experience: string;
  public_case: string;
  keyword_definition: string;
  fact_opinion_boundary: string;
  common_fallacy: string;
  low_quality_signal: string;
  qualified_standard: string;
  excellent_standard: string;
  scoring_dimensions: string;
  ai_feedback_strategy: string;
  recommended_format: string;
  source_ids: string;
  timeliness: string;
  safety_risk: string;
  needs_update: string;
  experience_answerable: string;
};

export type ResearchTopicSnapshotMeta = {
  schemaVersion: 2;
  sourceFile: "topics.json";
  topicCount: number;
  methodCount: number;
  sourceCount: number;
  categoryCounts: Record<string, number>;
  generatedAt: string;
  topicsSha256: string;
  methodsSha256: string;
  sourcesSha256: string;
};

export type ResearchMethod = {
  method_id: string;
  method_name: string;
  method_type: string;
  evidence_basis: string;
  target_level: string;
  target_skill: string;
  user_action: string;
  coach_action: string;
  duration: string;
  difficulty_progression: string;
  success_signal: string;
  failure_handling: string;
  oral_transfer: string;
  privacy_note: string;
  source_ids: string;
};

export type ResearchSource = {
  source_id: string;
  platform: string;
  title: string;
  author_or_publisher: string;
  published_date: string;
  collected_date: string;
  url: string;
  source_type: string;
  target_user: string;
  content_category: string;
  discussion_theme: string;
  core_summary: string;
  evidence_excerpt: string;
  trainable_skill: string;
  convertible_format: string;
  reliability_score: number;
  relevance_score: number;
  novelty_score: number;
  actionability_score: number;
  commercial_promotion: string;
  stance_bias: string;
  repost: string;
  copyright_notes: string;
  verification_status: string;
  access_note: string;
  score_basis: string;
};
