import { CalendarClock, CheckCircle2, History, Target, TrendingUp } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { EmptyState } from "../components/ui/EmptyState";
import { ProgressRing } from "../components/ui/ProgressRing";
import { SectionHeader } from "../components/ui/SectionHeader";
import { useDemoData } from "../data/useDemoData";

export function GrowthPage() {
  const navigate = useNavigate();
  const data = useDemoData();
  const latest = data.recentPractice[0];
  const observed = data.skillProgress.filter((skill) => skill.observationCount > 0);
  const mastery = observed.length > 0 ? Math.round(observed.reduce((sum, skill) => sum + skill.mastery, 0) / observed.length * 100) : 0;
  const pendingReviews = data.reviewItems.filter((item) => item.status === "pending");
  return <div className="page-container"><section className="growth-summary"><div><p className="micro-label text-primary-strong">SKILL SNAPSHOT · 技能快照</p><h2 className="mt-3 text-2xl font-bold">{latest ? "训练记录已经更新" : "完成一次训练后查看变化"}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ink-soft">{latest ? `最近一次得分 ${latest.score}，${latest.isRetry ? "来自聚焦重练" : "来自首次练习"}。` : "这里会展示可比较的维度分数、最近练习和待复习项目。"}</p></div><ProgressRing label="当前掌握" size={100} value={mastery} /></section>{latest ? <><section className="mt-8"><SectionHeader eyebrow="LATEST · 最近完成" title={latest.title} /><div className="mt-4 result-history-row"><div className="icon-tile bg-success-soft text-success"><CheckCircle2 size={21} /></div><div className="min-w-0 flex-1"><p className="font-bold">{latest.isRetry ? "聚焦重练已完成" : "首次练习已完成"}</p><p className="mt-1 text-sm text-ink-soft">{formatDate(latest.completedAt)} · 记录保存在此设备</p></div><strong>{latest.score}</strong></div></section><section className="mt-8"><SectionHeader eyebrow="DIMENSIONS · 维度变化" title="本次可观察结果" /><div className="mt-4 divide-y divide-line border-y border-line">{observed.map((skill) => <div className="skill-progress-row" key={skill.skillId}><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="font-bold">{skill.label}</span><span className="text-sm font-bold text-primary-strong">{skill.latestScore}</span></div><div className="progress-track mt-2"><span style={{ width: `${skill.mastery * 100}%` }} /></div><p className="mt-2 text-xs text-ink-muted">{skill.observationCount} 次有效观察 · 不确定度 {Math.round(skill.uncertainty * 100)}%</p></div></div>)}</div></section><section className="mt-8"><SectionHeader eyebrow="REVIEW · 待复习" title="把改进迁移到下一道题" /><div className="mt-4 flex items-start gap-3 border-y border-line py-4"><CalendarClock className="mt-0.5 shrink-0 text-warning" size={20} /><div><p className="font-bold">{pendingReviews.length} 个待复习项目</p><p className="mt-1 text-sm leading-6 text-ink-soft">{pendingReviews[0] ? `${formatDate(pendingReviews[0].dueAt)} 复习“具体贡献证据”。` : "当前没有到期项目。"}</p></div></div></section></> : <div className="mt-8"><EmptyState actionLabel="开始结构化表达" description="完成模拟录音和结果复盘后，技能进度会自动保存在这里。" onAction={() => navigate("/exercise/l2-project-contribution")} title="还没有可比较的训练记录" /></div>}<section className="mt-8 grid gap-3 sm:grid-cols-3"><div className="metric-tile"><History size={19} /><strong>{data.recentPractice.length}</strong><span>最近练习</span></div><div className="metric-tile"><Target size={19} /><strong>{observed.length}</strong><span>已观察维度</span></div><div className="metric-tile"><TrendingUp size={19} /><strong>{pendingReviews.length}</strong><span>待复习</span></div></section></div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
