import { Check, DatabaseBackup, LockKeyhole, RotateCcw, ShieldCheck, UserRound, X } from "lucide-react";
import { useState } from "react";
import { demoRepository } from "../data/demoRepository";
import { useDemoData } from "../data/useDemoData";
import type { UserProfile } from "../domain/models";

export function MePage() {
  const data = useDemoData();
  const [confirmReset, setConfirmReset] = useState(false);
  const [resetDone, setResetDone] = useState(false);
  const preferences = data.userProfile.privacyPreferences;
  const updatePreference = (key: keyof UserProfile["privacyPreferences"], value: boolean) => { demoRepository.updatePrivacyPreferences({ ...preferences, [key]: value }); setResetDone(false); };
  const reset = () => { demoRepository.reset(); setConfirmReset(false); setResetDone(true); };
  return <div className="page-container"><section className="flex items-center gap-4 border-b border-line pb-6"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary-soft text-primary-strong"><UserRound size={24} /></div><div><p className="text-xs text-ink-muted">当前身份</p><h2 className="mt-1 text-lg font-bold">{data.userProfile.displayName}</h2><p className="mt-1 text-sm text-ink-soft">目标：{data.userProfile.currentGoal}</p></div></section><section className="mt-8"><div><p className="micro-label text-ink-muted">PRIVACY · 隐私偏好</p><h2 className="mt-1 text-lg font-bold">本地演示数据</h2><p className="mt-2 text-sm leading-6 text-ink-soft">这些设置保存在当前浏览器，不会上传到服务器。</p></div><div className="mt-4 divide-y divide-line border-y border-line"><PreferenceToggle checked={preferences.saveSimulatedRecordings} description="当前没有真实音频，仅保存模拟录音状态。" label="保存模拟录音状态" onChange={(value) => updatePreference("saveSimulatedRecordings", value)} /><PreferenceToggle checked={preferences.retainTranscripts} description="用于在结果页显示证据片段和完整模拟转写。" label="保留模拟转写" onChange={(value) => updatePreference("retainTranscripts", value)} /><PreferenceToggle checked={preferences.allowModelImprovement} description="演示版不会发送数据；此项默认关闭。" label="允许用于模型改进" onChange={(value) => updatePreference("allowModelImprovement", value)} /></div></section><section className="mt-8"><div className="flex items-start gap-3 border-b border-line pb-4"><DatabaseBackup className="mt-0.5 text-primary-strong" size={20} /><div><h2 className="font-bold">当前保存内容</h2><p className="mt-1 text-sm leading-6 text-ink-soft">{data.recentPractice.length} 条练习记录 · {data.reviewItems.length} 个复习项目 · {Object.keys(data.evaluations).length} 份模拟结果</p></div></div>{resetDone && <div className="mt-4 flex items-center gap-2 rounded-md bg-success-soft p-3 text-sm font-semibold text-success"><Check size={17} />演示数据已重置</div>}{confirmReset ? <div className="reset-confirm mt-4"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 shrink-0 text-danger" size={19} /><div><h3 className="font-bold">确认重置全部演示数据？</h3><p className="mt-1 text-sm leading-6 text-ink-soft">练习记录、完成状态、筛选、结果和隐私偏好都会恢复初始值。</p></div></div><div className="mt-4 grid grid-cols-2 gap-3"><button className="secondary-button" onClick={() => setConfirmReset(false)} type="button"><X size={16} />取消</button><button className="primary-button bg-danger text-white" onClick={reset} type="button"><RotateCcw size={16} />确认重置</button></div></div> : <button className="secondary-button mt-5 text-danger" onClick={() => setConfirmReset(true)} type="button"><RotateCcw size={17} />重置演示数据</button>}</section><section className="mt-8 flex items-start gap-3 rounded-md bg-primary-soft p-4"><ShieldCheck className="mt-0.5 shrink-0 text-primary-strong" size={19} /><p className="text-sm leading-6 text-primary-strong">技术失败不会更新分数、技能进度或完成状态。</p></section></div>;
}

function PreferenceToggle({ checked, description, label, onChange }: { checked: boolean; description: string; label: string; onChange: (value: boolean) => void }) { return <div className="preference-row"><div className="min-w-0 flex-1"><p className="font-bold">{label}</p><p className="mt-1 text-sm leading-5 text-ink-soft">{description}</p></div><button aria-checked={checked} aria-label={`${label}，当前${checked ? "开启" : "关闭"}`} className={`switch-control ${checked ? "switch-control-on" : ""}`} onClick={() => onChange(!checked)} role="switch" type="button"><span /></button></div>; }
