import { ArrowRight, CheckCircle2, ChevronDown, Clock3, Quote, RotateCcw, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { FixedActionBar } from "../components/ui/FixedActionBar";
import { ProgressRing } from "../components/ui/ProgressRing";
import { l2ProjectExercise } from "../features/structured-expression/content";
import { createAttempt, getAttempt, getEvaluation } from "../features/structured-expression/storage";

export function TrainingResultPage() {
  const { attemptId } = useParams();
  const navigate = useNavigate();
  const attempt = getAttempt(attemptId ?? null);
  const result = getEvaluation(attemptId);
  if (!attempt || !result) return <MissingResult />;
  const isRetry = Boolean(attempt.retryOf);
  const retry = () => { const next = createAttempt(attempt.frameworkId, { retryOf: attempt.id, focusIssue: result.retry.focus }); navigate(`/focus/prepare?attemptId=${next.id}`); };
  return <div className="mx-auto w-full max-w-[720px] pb-28">
    <section className="result-summary"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="level-badge">L2 · {attempt.frameworkId}</span><span className="status-label"><CheckCircle2 size={14} />本次可评分</span></div><h2 className="mt-4 text-2xl font-bold">{result.overall.outcome}</h2><p className="mt-3 text-sm leading-6 text-ink-soft">评分依据当前任务、模拟转写和可观察结构生成。</p><div className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-md bg-primary-soft px-3 text-sm font-semibold text-primary-strong"><ShieldCheck size={17} />AI 评估置信度 {Math.round(result.confidence * 100)}%</div></div><ProgressRing label="本次得分" size={108} value={result.overall.score} /></section>
    <section className="result-section"><div className="result-section-title text-success"><CheckCircle2 size={20} /><div><p className="micro-label">STRENGTH · 有证据的优点</p><h3>{result.strength.title}</h3></div></div><p className="mt-4 text-sm leading-6 text-ink-soft">{result.strength.explanation}</p><EvidenceQuote quote={result.strength.evidence.quote} observation={result.strength.evidence.observation} /></section>
    <section className="result-section result-priority"><div className="result-section-title text-warning"><Target size={20} /><div><p className="micro-label">PRIORITY · 优先改进</p><h3>{result.priorityCorrection.title}</h3></div></div><p className="mt-4 text-sm leading-6 text-ink">{result.priorityCorrection.whyNow}</p><div className="mt-4 flex items-start gap-2 rounded-md bg-warning-soft p-3 text-sm leading-6 text-warning"><ArrowRight className="mt-1 shrink-0" size={16} /><span>{result.priorityCorrection.instruction}</span></div></section>
    <section className="result-section"><div className="result-section-title"><Quote className="text-primary-strong" size={20} /><div><p className="micro-label text-ink-muted">YOUR EVIDENCE · 原回答证据</p><h3>问题出现在这里</h3></div></div><EvidenceQuote quote={result.priorityCorrection.evidence.quote} observation={result.priorityCorrection.evidence.observation} /><details className="transcript-details mt-4"><summary>查看完整模拟转写 <ChevronDown size={16} /></summary><p>{result.transcript}</p></details></section>
    <section className="result-section"><div className="result-section-title"><Sparkles className="text-violet" size={20} /><div><p className="micro-label text-ink-muted">IMPROVED EXAMPLE · 改进示例</p><h3>保留原意，补全行动和结果</h3></div></div><p className="mt-4 text-[15px] leading-7 text-ink">{result.improvedExample}</p><p className="mt-3 text-xs leading-5 text-ink-muted">示例用于展示信息结构，不要求逐字背诵。</p></section>
    <section className="py-7"><div className="flex items-center gap-2"><Clock3 className="text-primary-strong" size={20} /><div><p className="micro-label text-ink-muted">{isRetry ? "TRANSFER · 重练完成" : "RETRY · 立即重练"}</p><h3 className="mt-1 text-lg font-bold">{isRetry ? "本次改进已经写入成长记录" : "只补一个具体行动和一个结果"}</h3></div></div><p className="mt-3 text-sm leading-6 text-ink-soft">{isRetry ? "前往成长页查看维度变化、最近练习和待复习项目。" : `准备 ${result.retry.preparationSeconds} 秒，仍使用 ${attempt.frameworkId}，表达上限 ${result.retry.speakingSeconds} 秒。`}</p></section>
    <section className="border-t border-line pt-7"><div><p className="micro-label text-ink-muted">DIMENSIONS · 维度评分</p><h3 className="mt-1 text-lg font-bold">展开查看评分证据</h3></div><div className="mt-4 divide-y divide-line border-y border-line">{result.dimensions.map((dimension) => <details className="dimension-detail" key={dimension.id}><summary><div className="min-w-0 flex-1"><span className="font-bold">{dimension.label}</span><p>{dimension.summary}</p></div><strong>{dimension.score}</strong><ChevronDown size={17} /></summary><div className="dimension-body"><EvidenceQuote quote={dimension.evidence[0].quote} observation={dimension.evidence[0].observation} />{dimension.nextBehavior && <p className="mt-3 text-sm leading-6 text-primary-strong">下一次：{dimension.nextBehavior}</p>}</div></details>)}</div></section>
    <FixedActionBar secondary={<button className="secondary-button" onClick={() => navigate("/home")} type="button">返回首页</button>} primary={isRetry ? <button className="primary-button" onClick={() => navigate("/growth")} type="button"><TrendingUp size={17} />查看成长</button> : <button aria-label="根据优先问题再次练习" className="primary-button" onClick={retry} type="button"><RotateCcw size={17} />聚焦重练</button>} />
  </div>;
}

function EvidenceQuote({ quote, observation }: { quote: string; observation: string }) { return <div className="evidence-quote mt-4"><Quote aria-hidden="true" size={17} /><div><blockquote>“{quote}”</blockquote><p>{observation}</p></div></div>; }
function MissingResult() { const navigate = useNavigate(); return <div className="state-panel"><h2 className="text-lg font-bold">结果还没有生成</h2><p className="mt-2 text-sm leading-6 text-ink-soft">训练记录可能已被清除，请重新完成一次模拟表达。</p><button className="primary-button mt-5" onClick={() => navigate(`/exercise/${l2ProjectExercise.id}`)} type="button">返回训练任务</button></div>; }
